site_name: Straight to the Kitchen Sink
site_author: Dishes Doge
site_description: WOW!! Lot of water! Such plates! Very cutlery!

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en

nav:
  - Home: index.md
